# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted version of kernel k-means algorithm to find local solutions to the optimization problem.
#'
#' @param X The data points matrix.
#' @param w A vector of weights associated to data points.
#' @param k The number of clusters.
#' @param iterations The number of iterations.
#' @param restarts The number of re-starts.
#' @param init_method The initialization method: "random" or "kpp".
#' @param method_name The optimization method: "lloyd" or "hardigan".
#' @export
kernel_biclustering <- function(X, k = 3L, iterations = 10L, restarts = 1L, init_method = "random", method_name = "hartigan", kernel_name = "rbf") {
    .Call(`_kernelbiclustering_kernel_biclustering`, X, k, iterations, restarts, init_method, method_name, kernel_name)
}

